name: 调试测试

on:
  workflow_dispatch: # 手动触发

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: data-processor/package-lock.json
        
    - name: 显示系统信息
      run: |
        echo "=== 系统信息 ==="
        echo "Node.js版本: $(node --version)"
        echo "npm版本: $(npm --version)"
        echo "系统信息: $(uname -a)"
        echo "内存信息: $(free -h)"
        echo "磁盘空间: $(df -h)"
        
    - name: 检查文件
      run: |
        echo "=== 文件检查 ==="
        cd data-processor
        echo "当前目录: $(pwd)"
        echo "文件列表:"
        ls -la
        echo ""
        echo "package.json内容:"
        cat package.json | head -20
        
    - name: 安装依赖
      run: |
        echo "=== 依赖安装 ==="
        cd data-processor
        echo "开始安装依赖..."
        npm ci --verbose
        echo "依赖安装完成"
        
    - name: 验证依赖
      run: |
        echo "=== 依赖验证 ==="
        cd data-processor
        echo "Node.js版本: $(node --version)"
        echo "npm列表:"
        npm list --depth=0
        
    - name: 运行调试脚本
      run: |
        echo "=== 运行调试脚本 ==="
        cd data-processor
        node debug-github-actions.js
        
    - name: 测试生产脚本
      run: |
        echo "=== 测试生产脚本 ==="
        cd data-processor
        echo "测试环境脚本..."
        node test-github-actions.js
        
    - name: 测试生产环境脚本
      run: |
        echo "=== 测试生产环境脚本 ==="
        cd data-processor
        echo "测试生产脚本（仅验证语法）..."
        node -c index-production.js
        echo "语法检查通过"
        
    - name: 检查Chrome
      run: |
        echo "=== Chrome检查 ==="
        which google-chrome || echo "Chrome未安装"
        which chromium-browser || echo "Chromium未安装"
        echo "Chrome相关包:"
        dpkg -l | grep chrome || echo "无Chrome包"
        
    - name: 网络测试
      run: |
        echo "=== 网络测试 ==="
        echo "测试npm注册表连接..."
        curl -I https://registry.npmjs.org/ || echo "npm注册表连接失败"
        echo "测试目标网站连接..."
        curl -I https://www.dongchedi.com/ || echo "目标网站连接失败" 