[build]
  # 发布目录
  publish = "."
  
  # 函数目录
  functions = "netlify/functions"
  
  # 构建命令（静态文件，无需构建）
  command = "echo 'Static site - no build required'"
  
  # 明确指定这是静态站点，不是Python项目

[functions]
  # 使用esbuild打包函数
  node_bundler = "esbuild"

[[headers]]
  # 为所有路由设置CORS头
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# 重定向规则
[[redirects]]
  # 将API请求重定向到Railway后端
  from = "/api/*"
  to = "https://dbtknight-production.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# 单页应用路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 