[build]
  # 发布目录
  publish = "."
  
  # 构建命令（静态文件，无需构建）
  command = ""

[[headers]]
  # 为所有路由设置CORS头
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# 重定向规则
[[redirects]]
  # 将API请求重定向到Vercel后端
  from = "/api/*"
  to = "https://api-2xaz3sa47-jonathan-jins-projects-32f77fb6.vercel.app/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# 单页应用路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 