[build]
  # 发布目录
  publish = "."
  
  # 函数目录
  functions = "netlify/functions"
  
  # 构建命令（静态文件，无需构建）
  command = ""
  
  # 忽略Python相关文件，避免Netlify误认为这是Python项目
  ignore = "runtime.txt, requirements.txt, render.py, render.yaml, api/, data-processor/"

[functions]
  # 使用esbuild打包函数
  node_bundler = "esbuild"

[[headers]]
  # 为所有路由设置CORS头
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# 重定向规则
[[redirects]]
  # 将API请求重定向到Render后端
  from = "/api/*"
  to = "https://dbtknight.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# 单页应用路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 