services:
  - type: web
    name: car-quote-backend
    env: python
    buildCommand: cd render-backend && pip install -r requirements.txt
    startCommand: cd render-backend && gunicorn render:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 